spring:
  application:
    name: appointment
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${NO_REPLY_EMAIL}
    password: ${NO_REPLY_EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          transport:
            protocol: smpts
resilience4j:
  ratelimiter:
    instances:
      auth-rate-limiter:
        limitForPeriod: 5
        limitRefreshPeriod: 120s
        timeoutDuration: 100ms

logging:
  level:
    liquibase: DEBUG
    org.springframework.security: DEBUG
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expiration: ${ACCESS_TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION}
  frontend:
    base-url: hospital-management-system





